

services:
  orbit_backend:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: orbit_backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: "node dist/main.js"